Adding Primitive POS with minimal features
frappe/books pull request #41
Opened 2018-06-12 12:35 UTC by nurdtechie98

Added a primitive POS system with item selector and invoice calculation feature. This how we explored vue.js and integrated it in the accounting package. Will keep adding functionalities one by one on a regular basis.

2018-06-13 04:45 UTC, rmehta commented
Share an animate GIF on how this works!

2018-06-13 04:50 UTC, rmehta requested changes

2018-06-13 04:50 UTC, rmehta commented on src/components/POS.vue
> +      items: [
query this with `frappe.db.getAll`

2018-06-13 04:50 UTC, rmehta commented on src/components/Transaction.vue
> +        <p v-if="!items.length">No items have been added.</p>
Add a "Make Invoice" button that will insert the items in the `Invoice` model, lets just make an invoice in the first cut, worry about payments later

2018-06-13 16:42 UTC, karan28598 commented
Integrated DB with list items and added invoice generation.
@rmehta, the features have been added.

2018-06-13 17:11 UTC, karan28598 commented
Integrated DB with list items and added invoice generation.
@rmehta, the features have been added. 
![pos](https://user-images.githubusercontent.com/25223215/41366822-e46dd9f2-6f5a-11e8-80fc-128966d7ec88.gif)

2018-06-14 14:50 UTC, nurdtechie98 commented
@rmehta all changes asked have been done, let us know for more changes and additions.

2018-06-18 07:56 UTC, nurdtechie98 commented
error alert messages added temp invoice object created

2018-06-25 05:45 UTC, netchampfaris requested changes

2018-06-25 05:45 UTC, netchampfaris commented on src/App.vue
> +    <frappe-modal ref="modal" :show="showModal" v-bind="modalOptions" @close-modal="showModal = false"/>
rebase with upstream/move-to-vue branch, this file shouldn't be in changed files

2018-06-25 05:45 UTC, netchampfaris commented on src/components/Numpad.vue
> +    font-size: 20px;
use `rem` instead of `px`

2018-06-25 05:45 UTC, netchampfaris commented on src/components/pos/POS.vue
> +<template>
let's put all POS related components in `src/pages/PointOfSale/`

2018-06-25 08:43 UTC, nurdtechie98 commented
@netchampfaris changes asked have been made pls review

2018-07-21 20:15 UTC, closed without merging