Initialize UOM model and create Warehouse model
frappe/books pull request #43
Opened 2018-06-14 17:50 UTC by Jaffrey98

#### The `UOM` model was initialized with the fields:
 - `name`  (Item Name) 
 - `uom` (Unit of Measure for the item)

#### The Warehouse model was created with the fields:
 - `name` (Warehouse name)
 - `parentWarehouse` (Name of parent warehouse (if exists) (else create one)
 - ` isGroup` (flag to identify whether warehouse is of type `group` or not)

> The `Warehouse` model has a functioning `tree view` that is generated by the desk and a `list view` to edit or delete the corresponding warehouse entry.

> The list view has the `warehouseName`, `type` ( i.e. `child` or `group` ) and if it has a parent warehouse  then it's `parentWarehouse` is mentioned.

Here is the GIF of the working of the `Warehouse` model:
![warehouse model working GIF](https://kek.gg/i/4PVb6B.gif)

 - GIF [link](https://kek.gg/i/4PVb6B.gif) (if at all the embedded one seems somewhat unclear 😅)
 - If the GIF is too fast here's the video [link](https://vimeo.com/275105013)

@rmehta @netchampfaris Please review and mention any changes to be done 🙏 .

2018-06-15 06:34 UTC, rmehta requested changes

2018-06-15 06:34 UTC, rmehta commented on client/index.js
> +	    frappe.desk.menu.addItem('Warehouse', '#tree/Warehouse');
check spacing

2018-06-15 06:34 UTC, rmehta commented on models/doctype/Uom/Uom.js
> +module.exports = {
How do you use this UOM?

UOM does not have an item property. They have a many-to-many relationship, so `Item UOM` should be a separate DocType

2018-06-15 06:34 UTC, rmehta commented on models/doctype/Uom/Uom.js
> +    naming: "random",
Naming of UOM should not be random! Should be the `name` property. See Item or Party

2018-06-15 06:34 UTC, rmehta commented on models/doctype/Warehouse/Warehouse.js
> +module.exports = {
check indentation

2018-06-17 15:57 UTC, Jaffrey98 commented
### Updated UOM model
 - Das single field `name`
 - Link created in Item model

### Working
 ![uom-updated-GIF](https://kek.gg/i/5YSwyP.gif)

 - GIF [link](https://kek.gg/i/5YSwyP.gif)
 - video [link](https://kek.gg/i/5YSwyP.gif)

2018-10-18 04:26 UTC, closed without merging